export const projects = [
    {
      title: "Frech Cart",
      desc: "Fresh Cart is an innovative e-commerce platform offering a wide range of fresh groceries, organic produce, and household essentials. With a user-friendly interface and seamless shopping experience.",
      imagePath: "./freshcart.png",
      liveDemoLink: "https://fresh-cart-swart.vercel.app/",
      githubLink: "https://github.com/1zizo1/Fresh-Cart.git",
      category: ["react", "mui"],
    },
    {
      title: "Yummy",
      desc: "A food recipe website where users can browse and search for recipes, with a focus on delicious and easy-to-make dishes.",
      imagePath: "./yummy.png",
      liveDemoLink: "https://1zizo1.github.io/Yummy/",
      githubLink: "https://github.com/1zizo1/Yummy.git",
      category: ["js", "css"],
    },
    {
      title: "Food Website",
      desc: "A responsive website for a restaurant or food delivery service, showcasing menus, special offers, and an online booking system.",
      imagePath: "./food website.png",
      liveDemoLink: "https://1zizo1.github.io/food-website/",
      githubLink: "https://github.com/1zizo1/food-website.git",
      category: ["js", "css"],
    },
    {
      title: "Game Over",
      desc: "A gaming review site where users can read reviews, see ratings, and browse through different game categories.",
      imagePath: "./gameover.png",
      liveDemoLink: "https://1zizo1.github.io/Game-Over/",
      githubLink: "https://github.com/1zizo1/Game-Over.git",
      category: ["js", "css"],
    },
    {
      title: "Devilo",
      desc: "A portfolio website template showcasing various projects, complete with live demos and GitHub repository links.",
      imagePath: "./devilio.jpg",
      liveDemoLink: "https://1zizo1.github.io/Devilo/",
      githubLink: "https://github.com/1zizo1/Devilo.git",
      category: ["js", "css"],
    },
    {
      title: "Daniels",
      desc: "A fictional website for a personal trainer or fitness instructor, featuring training programs, client testimonials, and contact information.",
      imagePath: "./daniels.png",
      liveDemoLink: "https://1zizo1.github.io/daniels/",
      githubLink: "https://github.com/1zizo1/daniels.git",
      category: ["js", "css"],
    },
    {
      title: "Mealify",
      desc: "An app for meal planning and grocery shopping, helping users create meal plans and generate shopping lists based on recipes.",
      imagePath: "./mealify.png",
      liveDemoLink: "https://1zizo1.github.io/mealify/",
      githubLink: "https://github.com/1zizo1/mealify.git",
      category: ["js", "css"],
    },
    {
      title: "Login System",
      desc: "A secure login and registration system with user authentication, built with modern web technologies.",
      imagePath: "./login system .png",
      liveDemoLink: "https://1zizo1.github.io/Login-System",
      githubLink: "https://github.com/1zizo1/Login-System",
      category: ["js", "css"],
    },
    {
      title: "Weather App",
      desc: "A weather forecasting app that provides current weather information and forecasts based on the user's location.",
      imagePath: "./weather.png",
      liveDemoLink: "https://1zizo1.github.io/weather-app",
      githubLink: "https://github.com/1zizo1/weather-app",
      category: ["js", "css"],
    },
    {
      title: "Bookmarker",
      desc: "A simple app to bookmark and manage favorite websites, allowing users to add, edit, and delete bookmarks.",
      imagePath: "./bookmarker.png",
      liveDemoLink: "https://1zizo1.github.io/bookmarker",
      githubLink: "https://github.com/1zizo1/bookmarker",
      category: ["js", "css"],
    },
    {
      title: "Training React",
      desc: "A training project for learning React, demonstrating various React features and best practices.",
      imagePath: "./trainig 1.3.png",
      liveDemoLink: "https://1zizo1.github.io/trainigReact",
      githubLink: "https://github.com/1zizo1/trainigReact",
      category: ["react","js", "css"],
    },
  ];